name: Finished Builds

on:
  push:
    branches:
        - main
    paths-ignore:
        - '**.md'
        - '.github/**'
        - '.gitignore'
  pull_request:
    branches:
        - main
    paths-ignore:
        - '**.md'
        - '.github/**'
        - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set current date as env variable # pacola if coyping from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows was a challenge:
      run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      
    - name: get PaK3 and the rest # now this is a fusion of the ntopp git and muder mystery git -pac
      run: | 
        sudo apt-get install -y nodejs
        git clone https://github.com/UnmatchedBracket/PaK3.git
        cd PaK3
        npm i

    - name: do the thing pls
      run: |
        mkdir build
        node PaK3/main.js src/ build/SpongebobSquigglepants-${{ env.NOW }}.pk3
    
    - name: send thing to the action tab
      uses: actions/upload-artifact@v4
      with:
        name: SpongebobSquigglepants
        path: build/SpongebobSquigglepants-${{ env.NOW }}.pk3

    - name: could you preetty please send the file to the discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: build/SpongebobSquigglepants-${{ env.NOW }}.pk3

    - name: gives us the commits pleaaase
      uses: Sniddl/discord-commits@v1.6
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: "Successful commit to **${{ github.ref_name }}**"
        template: "avatar-with-link"
        include-extras: true
