name: In-dev Builds

on:
  push:
    branches:
        - '**'
        - '!main'
  pull_request:
    branches:
        - '**'
        - '!main'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    
    steps:
      - name: Check changes :D
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E -v ".\.md|\.github/|\.vscode/|\.gitignore|.\.ase|.\.aseprite" || [[ ${{ github.event_name }} = "workflow_dispatch" }} ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: get all branches !!
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --all
          currentLoop=1
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
              if [ -n "$(git ls-tree --name-only $branch .ignore)" ] && [ "$branch" != "origin/main" ] || [ "$branch" == "origin" ]; then
                  echo $branch was skipped!
                  continue
              fi
              echo $branch is being merged
              git stash
              git merge $branch --no-commit --no-ff --allow-unrelated-histories -X theirs
              git reset origin/main
              git add .
              
              stashList=$(git stash list)
              if [ "$currentLoop" -gt 1 ] && [ "$stashList" != "" ]; then
                  git stash pop
              fi
              currentLoop=$((currentLoop+1))
              echo $branch was merged!
          done
          
      
      - name: Set current date as env variable # pacola if coyping from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows was a challenge:
        run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: do the thing pls
        run: |
          cd src/
          zip -r ../SpongebobSquigglepants-INDEV-${{ env.NOW }}.pk3 .
      
      - name: send thing to the action tab
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: Spongebob Squigglepants INDEV
          path: SpongebobSquigglepants-INDEV-${{ env.NOW }}.pk3

      - name: could you preetty please send the file to the discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: SpongebobSquigglepants-INDEV-${{ env.NOW }}.pk3

      - name: send the artifact link :P
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: "Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9"
        with:
          args: "Artifact can be found at [this cool link](${{ steps.artifact-upload.outputs.artifact-url }})"

  commits:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [check, build]

    steps:
      - name: gives us the commits pleaaase
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Successful commit to **${{ github.ref_name }}**"
          template: "avatar-with-link"
          include-extras: true